version: "3.7"

services:

  cloudflare-ddns:
    image: "docker.io/hectormolinero/supercronic:latest"
    restart: "on-failure:3"
    volumes:
      - "./crontab:/etc/crontab:ro"
      - "../cloudflare-ddns:/usr/local/bin/cloudflare-ddns:ro"
    environment:
      CLOUDFLARE_EMAIL: "${CLOUDFLARE_EMAIL}"
      CLOUDFLARE_API_KEY: "${CLOUDFLARE_API_KEY}"
      CLOUDFLARE_DNS_ZONE: "${CLOUDFLARE_DNS_ZONE}"
      CLOUDFLARE_DNS_ZONE_ID: "${CLOUDFLARE_DNS_ZONE_ID}"
      CLOUDFLARE_DNS_RECORD: "${CLOUDFLARE_DNS_RECORD}"
      CLOUDFLARE_DNS_RECORD_ID: "${CLOUDFLARE_DNS_RECORD_ID}"
